name: Test Code on Push

on:
  push:
    branches:
      - main  # Runs tests whenever code is pushed to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r app/requirements.txt

      - name: Run Code Linter (Check Formatting)
        run: |
          pip install flake8
          flake8 app/  # Runs Python linting to check for syntax errors
